kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster1
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30001
      hostPort: 30001
      protocol: TCP
    - containerPort: 30002
      hostPort: 30002
      protocol: TCP
    - containerPort: 30003
      hostPort: 30003
      protocol: TCP
    # extraMounts:
    # - hostPath: /root/k8s_for_openemr/kube/production/data/logvolume01
    #   containerPath: /mnt/data/logvolume01
    # - hostPath: /root/k8s_for_openemr/kube/production/data/sitevolume
    #   containerPath: /mnt/data/sitevolume
    # - hostPath: /root/k8s_for_openemr/kube/production/data/databasevolume
    #   containerPath: /mnt/data/databasevolume
  - role: worker
    # kubeadmConfigPatches:
    # - |
    #   kind: JoinConfiguration
    #   nodeRegistration:
    #     kubeletExtraArgs:
    #       node-labels: "environment=production,app=worker1"
  - role: worker
    # kubeadmConfigPatches:
    # - |
    #   kind: JoinConfiguration
    #   nodeRegistration:
    #     kubeletExtraArgs:
    #       node-labels: "environment=production,app=worker2"