apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mysql
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default  # Adjust if your MySQL service is in another namespace